title = "Secrets required to run the app"

[Database]
EMBEDDER_NAME = "clip-ViT-B-32"
QDRANT_URL = "https://5c325e69-b3d7-4ec7-83cb-4e295b8122a3.us-east4-0.gcp.cloud.qdrant.io:6333"
QDRANT_KEY = "QOJeQ-zqRmxPEfZYCNzHDPiSYDWZ2b8rWPrFTQjhiF2IVKg8-_cJkg"
COLLECTION_NAME = "artsper"